Fix some more Python 3 issue (unbufferend IO and str.decode)
When running with python3, we may end up with:

Traceback (most recent call last):
  File "/usr/bin/irqstat", line 401, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/irqstat", line 385, in main
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/usr/lib64/python3.8/os.py", line 1023, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O

And that's because unbuffered IO can't be done any
longer for text files.

Or with:

Traceback (most recent call last):
  File "./irqstat", line 401, in <module>
    sys.exit(main(sys.argv))
  File "./irqstat", line 385, in main
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/usr/lib64/python3.8/os.py", line 1023, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O

because of decode() not being there (and nor necessary)
for strings.

Fix both. For the former issue, if unbuffered IO is really
needed, the user can start the script with `python -u`.

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>