Workaround Python 3 not doing unbuffered IO for text files
On python3, running with -b cause this:

Traceback (most recent call last):
  File "/usr/bin/irqstat", line 401, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/irqstat", line 385, in main
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/usr/lib64/python3.8/os.py", line 1023, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O

That's because unbuffered IO can't be done any longer
(unless for binary IO).

Workaround that wrapping stdout in a stream that is always
flushed.

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>